# Generated by Django 4.1.4 on 2023-01-07 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_delete_perfil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
        migrations.AlterField(
            model_name='client',
            name='birthday',
            field=models.DateField(blank=True, verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='client',
            name='celphone',
            field=models.CharField(max_length=15, unique=True, verbose_name='Celphone'),
        ),
    ]
