# Generated by Django 4.1.4 on 2023-01-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='celphone',
            field=models.CharField(blank=True, max_length=15, unique=True, verbose_name='Celphone'),
        ),
    ]
