# Generated by Django 4.1.4 on 2022-12-30 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateTimeField(verbose_name='Delivery Date')),
                ('for_delivery', models.BooleanField()),
                ('delivery_method', models.CharField(blank=True, choices=[('Uber', 'Uber'), ('Personalized_VIP', 'Pernonalized VIP'), ('App_delivery', 'Delivery App outsourcing')], max_length=50)),
                ('delivery_address', models.CharField(blank=True, max_length=300)),
                ('comments', models.TextField(blank=True, max_length=500)),
                ('custumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
