# Generated by Django 4.1.4 on 2023-01-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='custumer',
            new_name='client',
        ),
        migrations.AddField(
            model_name='orders',
            name='status_payment',
            field=models.CharField(choices=[('NP', 'NOT PAID'), ('PG', 'PAID'), ('PE', 'PAID ENTRY')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='status_pedido',
            field=models.CharField(choices=[('CR', 'CREATED'), ('CL', 'CANCELED'), ('CF', 'CONFIRMED')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivery_method',
            field=models.CharField(blank=True, choices=[('P', 'Própia'), ('T', 'App Terceirizado')], max_length=1),
        ),
    ]
