# Generated by Django 4.1.4 on 2023-01-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_custumer_orders_client_orders_status_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status_payment',
            field=models.CharField(blank=True, choices=[('NP', 'NOT PAID'), ('PG', 'PAID'), ('PE', 'PAID ENTRY')], default='NP', max_length=2),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status_pedido',
            field=models.CharField(choices=[('CR', 'CREATED'), ('CL', 'CANCELED'), ('CF', 'CONFIRMED')], default='CR', max_length=2),
        ),
    ]
