# Generated by Django 4.1.4 on 2023-01-06 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orders_status_payment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=150)),
                ('product_id', models.PositiveIntegerField()),
                ('variation', models.CharField(max_length=150)),
                ('variation_id', models.PositiveIntegerField()),
                ('price', models.FloatField()),
                ('price_additional', models.FloatField(blank=True, default=0.0)),
                ('price_discount', models.FloatField(blank=True, default=0.0)),
                ('amount', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orders')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Itens',
            },
        ),
    ]
