# Generated by Django 4.1.4 on 2023-01-07 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_form',
            field=models.CharField(blank=True, choices=[('CS', 'CASH'), ('CC', 'CREDIT CARD'), ('DC', 'DEBIT CARD'), ('PX', 'PIX')], max_length=2, verbose_name='Payment Form'),
        ),
    ]
