# Generated by Django 4.1.4 on 2023-01-07 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_payment_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_form',
            field=models.CharField(blank=True, choices=[('CS', 'CASH'), ('CC', 'CREDIT CARD'), ('DC', 'DEBIT CARD'), ('PX', 'PIX')], default='PX', max_length=2, verbose_name='Payment Form'),
        ),
    ]
