# Generated by Django 4.1.4 on 2023-01-08 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_payment_form'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status_pedido',
            new_name='status_order',
        ),
    ]
