# Generated by Django 4.1.4 on 2023-01-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_created_at_order_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status_order',
            field=models.CharField(choices=[('CR', 'CREATED'), ('CL', 'CANCELED'), ('CF', 'CONFIRMED'), ('FN', 'FINISHED')], default='CR', max_length=2),
        ),
    ]
