# Generated by Django 4.1.4 on 2023-01-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_order_status_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(blank=True, choices=[('P', 'Própria'), ('T', 'App Terceirizado')], max_length=1),
        ),
    ]
