# Generated by Django 4.1.4 on 2023-01-16 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_order_delivery_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='sabor',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
