# Generated by Django 4.1.4 on 2023-01-06 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(verbose_name='Active')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('description_short', models.CharField(max_length=100, verbose_name='Short Description')),
                ('description_long', models.CharField(max_length=300, verbose_name='Long Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/%Y/%m/', verbose_name='Product Image')),
                ('slug', models.SlugField(unique=True)),
                ('value', models.FloatField()),
                ('type', models.CharField(choices=[('V', 'Variable'), ('S', 'Simple')], max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
    ]
