# Generated by Django 4.1.4 on 2023-01-06 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_options_rename_value_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description_long',
            field=models.CharField(blank=True, max_length=300, verbose_name='Long Description'),
        ),
    ]
