# Generated by Django 4.1.4 on 2023-01-16 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_description_long_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='sabor',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
